version: "3.7"
services:
  frontend:
    image: frozosea/fmc-frontend:latest
    ports:
      - "8080:8080"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./:/var/www"
    depends_on:
      - frontend
    networks:
      - public

networks:
  public:
    name: public
    external: true