version: "3.7"
services:
  frontend:
    image: flyasea/fmc-frontend:latest
    ports:
      - "80:80"
    environment:
      VUE_APP_BACKEND_URL: https://api.findmycargo.ru

networks:
  public:
    name: public
    external: true