<template>
  <long-dotted-line/>
  <div style="margin: 20px">
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:2.85pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:center;"><strong><span style="font-size:16px;color:black;">ПОЛЬЗОВАТЕЛЬСКОЕ СОГЛАШЕНИЕ ДЛЯ ВЕБ-САЙТА</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:center;"><strong><span style="font-size:16px;color:black;">1. ОПРЕДЕЛЕНИЕ ПОНЯТИЙ</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;text-indent:22.5pt;"><span style="font-size:16px;color:black;">В тексте настоящего Соглашения нижеизложенным терминам дано следующее значение:</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;text-indent:22.5pt;"><span style="font-size:16px;color:black;">&quot;<strong>Сайт</strong>&quot; означает следующий сайт: FindMyCargo, который принадлежит Компании и находится по следующей ссылке: https://findmycargo.ru.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;text-indent:22.5pt;"><span style="font-size:16px;color:black;">&quot;<strong>Пользователь</strong>&quot;, &quot;<strong>Вы</strong>&quot;, &quot;<strong>Ваш</strong>&quot;, &quot;<strong>Вас</strong>&quot;, &quot;<strong>Вами</strong>&quot; или какие-либо другие схожие производные (в зависимости от контекста) означает лицо, которое <strong>(1)</strong> пользуется Сайтом и/или получило доступ к его Контенту; и <strong>(2)</strong> дало свое согласие на соблюдение правил пользования Сайтом, изложенных в тексте данного Соглашения, путем использования данного Сайта.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;text-indent:22.5pt;"><span style="font-size:16px;color:black;">&quot;<strong>Компания</strong>&quot;, &quot;<strong>Мы</strong>&quot;, &quot;<strong>Наш</strong>&quot;, &quot;<strong>Нас</strong>&quot;, &quot;<strong>Нами</strong>&quot; или какие-либо другие схожие производные (в зависимости от контекста) означает следующее лицо: ООО&quot;МОЯ ЛОГИСТИКА&quot;, адрес местонахождения: 692940, Россия, Приморский край, г. Находка, микрорайон Врангель, ул. Крайнева, д. 8 пом. 17 (включая, его филиалы и представительства как на территории Российской Федерации, так и за ее пределами, а также какие-либо другие лица, созданные в результате реорганизации Компании), которое является владельцем Сайта или им управляет.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;text-indent:22.5pt;"><span style="font-size:16px;color:black;">&quot;<strong>Контент сайта</strong>&quot; означает все объекты, размещенные Компанией и/или третьими лицами (с разрешения Компании) на Сайте, в том числе элементы дизайна, текст, графические изображения, иллюстрации, видео, программы, музыка, звуки, информация, уведомления и какие-либо другие объекты схожего назначения, их подборки или комбинации.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;text-indent:22.5pt;"><span style="font-size:16px;color:black;">&quot;<strong>ПО сайта</strong>&quot; означает программное обеспечение, разработанное Компанией (и/или третьими лицами по поручению Компании) для Сайта, включая, однако не ограничиваясь, весь софт, скрипты, коды (HTML коды), программы и тп.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;text-indent:22.5pt;"><span style="font-size:16px;color:black;">&quot;<strong>Услуги</strong>&quot; означает совокупно Контент сайта и ПО сайта.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:center;"><strong><span style="font-size:16px;color:black;"><br>&nbsp;<br>&nbsp;2. ПРИСОЕДИНЕНИЕ К СОГЛАШЕНИЮ</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">2.1. Пользователи используют Сайт для следующих целей:</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><em><span style="font-size:16px;color:black;">Цифровая автоматизация рутинных процессов в сфере морских грузовых перевозок.&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;<br>&nbsp;Предоставление доступа к актуальной информации о состоянии и местоположении морского груза.</span></em></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">2.2. Настоящее Пользовательское соглашение (далее &quot;<strong>Соглашение</strong>&quot;) определяет правила и порядок использования Сайта и Услуг, права и обязанности Пользователей, а также регулирует поведение Пользователей при получении доступа к Сайту и Услугам.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">2.3. Пользователь принимает условия данного Соглашения посредством продолжения использования Сайта.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">2.4. Данное Соглашение является обязательным для его сторон (т.е. для Компании и Пользователя). Уступка Пользователем своих прав по данному Соглашению возможна только после получения предварительного письменного согласия от Компании.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:center;"><strong><span style="font-size:16px;color:black;"><br>&nbsp;<br>&nbsp;3. ПОЛЬЗОВАТЕЛИ САЙТА</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">Общие критерии и возраст</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">3.1. Для использования Сайта Пользователи должны соответствовать следующим критериям (совокупно):</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">(1)</span></strong><span style="font-size:16px;color:black;">&nbsp;быть не младше 6-лет; и</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">(2)</span></strong><span style="font-size:16px;color:black;">&nbsp;не быть ограниченным в праве доступа к Сайту и Услугам на основании решения суда, вступившего в законную силу, или в случаях, предусмотренных действующим законодательством или условиями данного Соглашения; и</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">(3)</span></strong><span style="font-size:16px;color:black;">&nbsp;соблюдать следующие условия/выполнять критерии:</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><em><span style="font-size:16px;color:black;">Являться юридическим или физическим лицом.&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<br>&nbsp;Находиться в адекватном психическом и психологическом состоянии.</span></em></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">Регистрация на сайте и создание личного аккаунта</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">3.2. Использование данного Сайта возможно как Пользователями, которые прошли процедуру бесплатной регистрации и создали свой личный аккаунт (кабинет), так и Пользователями, которые отказались от такой регистрации. Незарегистрированные Пользователи не имеют доступа к следующим Услугам:</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><em><span style="font-size:16px;color:black;">(1)Установка контейнеров на слежение по расписанию. (2)Установка коносаментов на слежение по расписанию. (3) Доступ к личному кабинету. (4) Доступ к функционалу, позволяющему искать поставщиков фрахта.</span></em></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">3.3. Для снятия указанных ограничений и получения полного доступа Пользователю необходимо пройти регистрацию на Сайте. По результатам завершения регистрации Пользователь получает уникальный логин и пароль.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">3.4. Действие данного Соглашения распространяется одинаково в полном объеме (без каких-либо исключений) как на зарегистрированных, так и на незарегистрированных Пользователей.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">3.5. Для регистрации Пользователю необходимо предоставить следующею информацию о себе:</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">Регистрация для частных лиц:</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><em><span style="font-size:16px;color:black;">электронный адрес</span></em></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">Регистрация для бизнеса:</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><em><span style="font-size:16px;color:black;">(1)Имя компании полное&nbsp; &nbsp; &nbsp;&nbsp;<br>&nbsp;(2)Имя компании сокращенное&nbsp; &nbsp; &nbsp;&nbsp;<br>&nbsp;(3)ИНН&nbsp; &nbsp;&nbsp;<br>&nbsp;(4)ОГРН&nbsp;&nbsp;<br>&nbsp;(5)Полный юридический адрес&nbsp; &nbsp;&nbsp;&nbsp;<br>&nbsp;(6)Почтовый адрес&nbsp; &nbsp;&nbsp;&nbsp;<br>&nbsp;(7)Рабочий адрес электронной почты&nbsp; &nbsp;&nbsp;&nbsp;<br>&nbsp;(8)ЭДО (если имеется)&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;<br>&nbsp;(9)Сфера деятельности&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;<br>&nbsp;(10)Электронный адрес</span></em></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:center;"><strong><span style="font-size:16px;color:black;"><br>&nbsp;<br>&nbsp;4. ИНТЕЛЛЕКТУАЛЬНАЯ СОБСТВЕННОСТЬ</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">4.1. Компании принадлежат все без исключения права собственности, включая имущественные права интеллектуальной собственности, на весь Контент сайта, а также ПО сайта. ПО сайта и Контент сайта защищены авторским правом в порядке, предусмотренном действующим гражданским законодательством Российской Федерации, а также международными договорами и конвенциями в области защиты объектов интеллектуальной собственности.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">4.2. Пользователям запрещено копировать, воспроизводить, модифицировать, компилировать, распространять, отображать в какой-либо форме, публиковать, скачивать, передавать, продавать или иным способом распространять или использовать Контент сайта и ПО сайта, кроме случаев, когда такие действия ПРЯМО разрешены условиями данного Соглашения или действующим законодательством Российской Федерации.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">4.3. Ничто в тексте данного Соглашения не может быть истолковано как передача Пользователю каких-либо исключительных прав на Контент сайта (полностью или в отдельной части) и/или ПО сайта.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:center;"><strong><span style="font-size:16px;color:black;"><br>&nbsp;<br>&nbsp;5. ПОРЯДОК РАБОТЫ С САЙТОМ</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">Правила поведения на сайте</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">5.1. Во время использования Сайта Пользователь обязуется придерживаться следующих правил:</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">(1)</span></strong><span style="font-size:16px;color:black;">&nbsp;соблюдать все обязательства, взятые на себя Пользователем в связи с присоединением к данному Соглашению; и</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">(2)</span></strong><span style="font-size:16px;color:black;">&nbsp;предоставлять достоверные о себе данные во время регистрации на Сайте и для создания личного аккаунта (кабинета); и</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">(3)</span></strong><span style="font-size:16px;color:black;">&nbsp;не выдавать себя за какое-либо другое лицо, включая, однако не ограничиваясь, не предоставлять какие-либо данные третьих лиц (без получения от них прямого, предварительного и осознанного согласия) для регистрации на Сайте и/или для создания личного аккаунта (кабинета); и</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">(4)</span></strong><span style="font-size:16px;color:black;">&nbsp;информировать Компанию о хищении логинов, паролей или каких-либо других ключей доступа Пользователя к личному аккаунту (кабинету); и</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">(5)</span></strong><span style="font-size:16px;color:black;">&nbsp;не предоставлять третьим лицам доступ к своему аккаунту (кабинету) и/или логины, пароли или другие ключи доступа; и</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">(6)</span></strong><span style="font-size:16px;color:black;">&nbsp;не совершать какие-либо действия (с использованием средств автоматизации или без таких средств), направленные на сбор каких-либо персональных данных других Пользователей; и</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">(7)</span></strong><span style="font-size:16px;color:black;">&nbsp;не предпринимать какие-либо действия и не помогать третьим лицам в совершении действий, направленных на подрыв работы Сайта, включая, однако не ограничиваясь, <strong>(а)</strong> загружать вирусы или вредоносный код; <strong>(б)</strong> совершать действия, которые могут привести к отключению Сайта, к нарушению нормальной работы Сайта или ПО сайта, или к ухудшению внешнего вида Сайта и/или Контента Сайта.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">(8)</span></strong><span style="font-size:16px;color:black;">&nbsp;не предпринимать какие-либо иные действия, которые являются незаконными, мошенническими, дискриминационными или вводящими в заблуждение.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">Отзывы о работе сайта</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">5.2. Каждый Пользователь время от времени имеет право (но не обязанность) оставлять или направлять свои идеи, отзывы, предложения или проекты, направленные на улучшение работы Сайта или качества предоставляемых Услуг. Такие отзывы могут быть направлены Пользователем следующим способом:</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><em><span style="font-size:16px;color:black;">(1)Отправить письмо на следующие адреса электронной почты: feedback@findmycargo.ru, feedback@mailing.findmycargo.ru, ceo@findmycargo.ru, feedback@mailing.findmycargo.ru.&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;<br>&nbsp;(2)Воспользоваться формой для обратной связи.</span></em></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">5.3. В случае направления такой идеи, отзыва, предложения или проекта Пользователь автоматически предоставляет нам неисключительную, не требующую лицензионных отчислений, действующую по всему миру лицензию с правом передачи и выдачи сублицензий на хранение, использование, распространение, изменение, запуск, копирование, публичное исполнение или показ, перевод Ваших идей, отзывов, предложений или проектов, а также создание производных работ на их основе.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:center;"><strong><span style="font-size:16px;color:black;"><br>&nbsp;<br>&nbsp;6. РАЗМЕЩЕНИЕ РЕКЛАМЫ НА САЙТЕ</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">Размещение рекламы компанией</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">6.1. Компания имеет право время от времени размещать на Сайте какие-либо рекламные или маркетинговые материалы.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">Размещение рекламы третьими лицами</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">6.2. Контент сайта может содержать ссылки на веб-сайты третьих лиц и/или рекламные или маркетинговые материалы о товарах/услугах, предоставленные такими третьими лицами (далее &quot;<strong>Реклама третьих лиц</strong>&quot;). КОМПАНИЯ НЕ БЕРЕТ НА СЕБЯ КАКУЮ-ЛИБО ОТВЕТСТВЕННОСТЬ <strong>(1)</strong> ЗА СОДЕРЖАНИЕ РЕКЛАМЫ ТРЕТЬИХ ЛИЦ, А ТАКЖЕ ЗА НАЛИЧИЕ, КАЧЕСТВО И БЕЗОПАСНОСТЬ ПРОДВИГАЕМЫХ ТОВАРОВ/УСЛУГ В ТАКОЙ РЕКЛАМЕ; и <strong>(2)</strong> ЗА КАКИЕ-ЛИБО УБЫТКИ, ПОТЕРИ ИЛИ УЩЕРБ, ПОНЕСЕННЫЕ ИЛИ ПРИЧИНЕННЫЕ ПОЛЬЗОВАТЕЛЮ В РЕЗУЛЬТАТЕ ПРОЧТЕНИЯ ИМ ТАКОЙ РЕКЛАМЫ, ИСПОЛЬЗОВАНИЯ ИМ ПРОДВИГАЕМЫХ В РЕКЛАМЕ ТРЕТЬИХ ЛИЦ ТОВАРОВ/УСЛУГ.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">6.3. В случае перехода на другой сайт через размещенную на Сайте Рекламу третьих лиц, Компания не может гарантировать, что такой веб-сайт является безопасным для Пользователя и/или его компьютера. Ни что в тексте данного Соглашения не должно быть истолковано как заверение, поощрение, рекомендация или побуждение Пользователя воспользоваться Рекламой третьих лиц, посетить какие-либо сайты третьих лиц, а также попробовать, приобрести, воспользоваться какими-либо товарами/услугами третьих лиц.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">6.4. Вопросы, связанные с защитой персональных данных Пользователей при использовании ими Рекламы третьих лиц, регулируются Политикой обработки персональных данных.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:center;"><strong><span style="font-size:16px;color:black;"><br>&nbsp;<br>&nbsp;7. СОВЕРШЕНИЕ ПОКУПОК ЧЕРЕЗ САЙТ</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">7.1. Сайт временно не предоставляет возможность покупки каких-либо товаров/услуг через него.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:center;"><strong><span style="font-size:16px;color:black;"><br>&nbsp;<br>&nbsp;8. ОФОРМЛЕНИЕ ПОДПИСКИ НА САЙТЕ</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">8.1. Доступ к Сайту и к его Услугам не предполагает от Пользователей оформления какой-либо подписки.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:center;"><strong><span style="font-size:16px;color:black;"><br>&nbsp;<br>&nbsp;9. ПРЕКРАЩЕНИЕ ДОСТУПА К САЙТУ</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">9.1. Пользователь имеет право в любой момент прекратить использование Сайта посредством удаления своего аккаунта:</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><em><span style="font-size:16px;color:black;">(1) Написать письмо на следующие адреса электронной почты: support@findmycargo.ru, support@mailing.findmycargo.ru. С темой письма: &quot;Запрос об удалении персонального аккаунта с сайта&quot;. В теле письма должны быть указанные идентификационные данные пользователя, а именно: 1)Адрес электронный почты 2)Никнейм пользователя 3)Пароль.&nbsp; &nbsp;&nbsp;&nbsp;<br>&nbsp;(2)Воспользоваться формой обратной связи на сайте. Первым абзацем письма должна быть указана тема письма, а именно: &quot;Запрос об удалении персонального аккаунта с сайта&quot;. В теле запроса должны быть указанные идентификационные данные пользователя, а именно: 1)Адрес электронный почты 2)Никнейм пользователя 3)Пароль.</span></em></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">9.2. В случае <strong>(1)</strong> нарушения Пользователем условий настоящего Соглашения; и/или <strong>(2)</strong> нарушения прав интеллектуальной собственности Компании, других Пользователей или третьих лиц; и/или <strong>(3)</strong> совершения действий, которые являются противозаконными, нарушают права и интересы Компании, других Пользователей или третьих лиц или подрывают работу Сайта или возможность использования Сайта другими Пользователями; и/или <strong>(4)</strong> Услуги или Сайт используется Пользователем таким образом, что это может повлечь юридическую ответственность Компании в будущем; и/или <strong>(5)</strong> если этого требует действующее законодательство или компетентный государственный орган, Компания имеет право без предварительного уведомления в любой момент прекратить (остановить) доступ Пользователя к Сайту и его Услугам.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">9.3. Такое прекращение доступа кроме прочего также подразумевает удаление личного аккаунта Пользователя.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">9.4. Пользователь должным образом осведомлен, что Компания не берет на себя ответственность за какой-либо ущерб, убытки, упущенную выгоду, потерю деловой или личной репутации, причиненные Пользователю удалением или блокировкой аккаунта и/или невозможностью доступа к Сайту и его Услугам.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:center;"><strong><span style="font-size:16px;color:black;"><br>&nbsp;<br>&nbsp;10. ЗАДАТЬ ВОПРОС</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">10.1. Если у Вас есть вопросы касательно условий настоящего Соглашения или порядка/способа их исполнения, Вы можете адресовать нам свой вопрос следующим способом:</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><em><span style="font-size:16px;color:black;">(1)Написать письмо на следующие адреса электронной почты: support@findmycargo.ru, support@mailing.findmycargo.ru. Тема письма: &quot;Трактовка отдельных пунктов пользовательского соглашения&quot;. В теле письма указать интересующий вопрос.&nbsp;&nbsp;&nbsp;<br>&nbsp;(2)Воспользоваться формой обратной связи на сайте.</span></em></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">10.2. Сотрудники и представители Компании обязуются предпринять все возможные усилия для дачи ответа на Ваш запрос в течение разумного периода времени.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:center;"><strong><span style="font-size:16px;color:black;"><br>&nbsp;<br>&nbsp;11. ОТВЕТСТВЕННОСТЬ</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">11.1. НИ ПРИ КАКИХ ОБСТОЯТЕЛЬСТВАХ КОМПАНИЯ ИЛИ ЕЕ ПРЕДСТАВИТЕЛИ НЕ НЕСУТ ОТВЕТСТВЕННОСТЬ ПЕРЕД ПОЛЬЗОВАТЕЛЕМ ИЛИ ПЕРЕД ЛЮБЫМИ ТРЕТЬИМИ ЛИЦАМИ:</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">(1)</span></strong><span style="font-size:16px;color:black;">&nbsp;ЗА ЛЮБОЙ КОСВЕННЫЙ, СЛУЧАЙНЫЙ, НЕУМЫШЛЕННЫЙ УЩЕРБ, ВКЛЮЧАЯ УПУЩЕННУЮ ВЫГОДУ ИЛИ ПОТЕРЯННЫЕ ДАННЫЕ, ВРЕД ЧЕСТИ, ДОСТОИНСТВУ ИЛИ ДЕЛОВОЙ РЕПУТАЦИИ, ВЫЗВАННЫЙ В СВЯЗИ С ИСПОЛЬЗОВАНИЕМ САЙТА, УСЛУГ ИЛИ ИНЫХ МАТЕРИАЛОВ, К КОТОРЫМ ПОЛЬЗОВАТЕЛЬ ИЛИ ИНЫЕ ЛИЦА ПОЛУЧИЛИ ДОСТУП С ПОМОЩЬЮ САЙТА, ДАЖЕ ЕСЛИ КОМПАНИЯ ПРЕДУПРЕЖДАЛА ИЛИ УКАЗЫВАЛА НА ВОЗМОЖНОСТЬ ТАКОГО ВРЕДА; и</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">(2)</span></strong><span style="font-size:16px;color:black;">&nbsp;ЗА ДЕЙСТВИЯ ДРУГИХ ПОЛЬЗОВАТЕЛЕЙ, ЗА РАЗМЕЩАЕМЫЙ ПОЛЬЗОВАТЕЛЯМИ ПОЛЬЗОВАТЕЛЬСКИЙ КОНТЕНТ, ЗА ТОВАРЫ/УСЛУГИ, ПРЕДОСТАВЛЯЕМЫЕ ТРЕТЬИМИ ЛИЦАМИ ИЛИ ДРУГИМИ ПОЛЬЗОВАТЕЛЯМИ (ДАЖЕ ЕСЛИ ДОСТУП К НИМ БЫЛ ПРЕДОСТАВЛЕН ЧЕРЕЗ НАШ САЙТ), К КОТОРЫМ ПОЛЬЗОВАТЕЛЬ ПОЛУЧИЛ ДОСТУП; и</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><strong><span style="font-size:16px;color:black;">(3)</span></strong><span style="font-size:16px;color:black;">&nbsp;в случаях прямо предусмотренных условиями настоящего Соглашения или нормой действующего законодательства.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">11.2. Наша ответственность за все что угодно, связанное с использованием Сайта и/или Услуг, ограничивается настолько сильно, насколько это допускается действующим законодательством.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:center;"><strong><span style="font-size:16px;color:black;"><br>&nbsp;<br>&nbsp;12. ПОРЯДОК РАЗРЕШЕНИЯ СПОРОВ</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">12.1. В случае возникновения любых споров или разногласий, связанных с исполнением настоящего Соглашения, Пользователь и Компания приложат все усилия для их разрешения путем проведения переговоров между ними. В случае, если споры не будут разрешены путем переговоров, споры подлежат разрешению в порядке, установленном действующим законодательством Российской Федерации.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:22.5pt;line-height:normal;font-size:15px;font-family:Helvetica;text-align:center;"><strong><span style="font-size:16px;color:black;"><br>&nbsp;<br>&nbsp;13. ЗАКЛЮЧИТЕЛЬНЫЕ ПОЛОЖЕНИЯ</span></strong></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">13.1. Настоящее Соглашение вступает в силу с момента его опубликования на Сайте (по следующей ссылке:&nbsp;</span><span style="font-size:16px;color:black;">https</span><span style="font-size:16px;color:black;">://</span><span style="font-size:16px;color:black;">findmycargo</span><span style="font-size:16px;color:black;">.</span><span style="font-size:16px;color:black;">ru</span><span style="font-size:16px;color:black;">) и действуют в течение неопределенного периода времени.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">13.2. Мы можем время от времени пересматривать, дополнять или изменять условия данного Соглашения. Такие изменения, как правило, не являются ретроспективными. КОМПАНИЯ НЕ БЕРЕТ НА СЕБЯ КАКУЮ-ЛИБО ОБЯЗАННОСТЬ ПО УВЕДОМЛЕНИЮ ПОЛЬЗОВАТЕЛЕЙ О ПРЕДСТОЯЩИХ ИЛИ СОСТОЯВШИХСЯ ИЗМЕНЕНИЯХ ТЕКСТА СОГЛАШЕНИЯ. Посредством присоединения к условиям данного Соглашения Пользователь также берет на себя обязательство периодически просматривать условия данного Соглашения на предмет их изменения или дополнения.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">Если после проведенных изменений или дополнений в тексте Соглашения Пользователь продолжает пользоваться Сайтом, это значит, что он ознакомлен с изменениями или дополнениями и их принял в полном объеме без каких-либо возражений.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">13.3. Если иное прямо не указано в положениях настоящего Соглашения или прямо не вытекает из норм действующего законодательства, к условиям настоящего Договора применяется материальное право Российской Федерации.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">13.4. Неотъемлемой частью настоящего Соглашение является Политика обработки персональных данных.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">13.5. Если одно или несколько условий данного Соглашения утратило свою юридическую силу или признано недействительным согласно действующему законодательству, остальные условия Соглашения не теряют своей силы и продолжают действовать так, словно признанного недействительным или утратившим юридическую силу условия не существовало вовсе.</span></p>
    <p style="margin-top:12.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:Helvetica;text-align:justify;"><span style="font-size:16px;color:black;">13.6. Доступ к Сайту и его Услугам предоставляется Пользователю &quot;как есть&quot;, Мы не обещаем, не гарантируем, не подразумеваем, что Услуги и Сайт могут подходить или не подходить Вашим потребностям, целям, ожиданиям, и в связи с чем не гарантируем какого-либо специфического результата или последствия в результате использования Вами Сайта и его Услуг.</span></p>
  </div>
</template>

<script>
import LongDottedLine from "@/UI/longDottedLine";
export default {
  name: "userAgreement",
  components: {LongDottedLine},
  async mounted(){
    if (this.$store.getters[`user/getIsAuth`]) {
      await this.$store.commit(`refreshToken`)
    }
    window.scrollTo({
      top: 0,
      left: 0,
      behavior: 'smooth'
    });
  }
}
</script>

<style scoped>

</style>